"""Remove unique constraints

Revision ID: 329098f248b7
Revises: 49e60a818ba8
Create Date: 2024-12-01 18:20:28.888110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329098f248b7'
down_revision: Union[str, None] = '49e60a818ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_document_id', table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_document_id', 'documents', ['document_id'], unique=True)
    # ### end Alembic commands ###
