"""initial migration

Revision ID: 49e60a818ba8
Revises: 
Create Date: 2024-12-01 18:13:24.675733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e60a818ba8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('extraction_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issue_location', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('issuing_agency', sa.String(length=200), nullable=True),
    sa.Column('recipients', sa.String(length=500), nullable=True),
    sa.Column('recipient_address', sa.Text(), nullable=True),
    sa.Column('signer', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('page_numbers', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extraction_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('text_regions', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issue_location', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('issuing_agency', sa.String(length=200), nullable=True),
    sa.Column('recipients', sa.String(length=500), nullable=True),
    sa.Column('recipient_address', sa.String(length=500), nullable=True),
    sa.Column('signer', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
