"""Add MinIO fields to documents table

Revision ID: add_minio_fields
Revises: 
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_minio_fields'
down_revision = '329098f248b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('input_file_url', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('output_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'output_urls')
    op.drop_column('documents', 'input_file_url')
    # ### end Alembic commands ###
